// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://smcslhsasuwzwgomhjug.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InNtY3NsaHNhc3V3endnb21oanVnIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDg5NTU1NTcsImV4cCI6MjA2NDUzMTU1N30.qDpUzYPchDkqayXdWGZjwfJa82iL1FARzV_axCMpzlk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);